feat(scale-test): scripts that generates, run apps and collect results
openebs/performance-benchmark pull request #10
Opened 2020-02-18 13:45 UTC by vishnuitta

This `scale-test` directory contains scripts and templated yamls to generate required number of application pods yaml and apply these yamls.
After test is completed, scripts takes care of collecting fio outputs into local machine's <curdir>/<testid> and prints the IOPS/latency snippets of fio output.
These scripts also takes care of any cleanup required during the start of test, and also does cleanup at the end of test.

More info is updated in README.md

Signed-off-by: Vitta <vitta@mayadata.io>

2020-02-24 06:13 UTC, ksatchit commented
Thanks for the scripts @vishnuitta !

2020-02-29 18:54 UTC, kmova commented on scale-test/fioload-template.yaml
> +      path: /home/vitta/fio-results/@testid@
n_ : Should the hardcoding to vitta be removed.

2020-02-29 18:58 UTC, kmova approved these changes
I glanced through the changes once and looks good to me. An additional detailed review will be helpful.

2020-05-21 12:57 UTC, gila requested changes

2020-05-21 12:57 UTC, gila commented on scale-test/README.md
> +This `scale-test` directory contains scripts and templated yamls to generate required number of application pods yaml and apply these yamls.
Please remove the swap file from your editor of this commit

2020-05-21 12:57 UTC, gila commented on scale-test/fioload-template.yaml
> +    - 'fio --blocksize=@bs@ --verify=0 --randrepeat=0 --filename=/mnt/file1 --ioengine=libaio --readwrite=randread --runtime=60s --time_based --ramp_time=2s --size=3G --name=test --numjobs=8 --direct
Fio has an option to specify the output file, I would use that as it is also not needed to collect the interval updates that fio produces.

2020-05-21 12:57 UTC, gila commented on scale-test/fioload-template.yaml
> +        fio --blocksize=@bs@ --verify=0 --randrepeat=0 --filename=/mnt/file2 --ioengine=libaio --readwrite=randread --runtime=15s --time_based --ramp_time=2s --size=3G --name=test --direct=1 --group_
You are running fio twice? Can you explain what the idea behind that is? Also, why do you need to sleep for the file to be created? If you want to have jobs completed, or started in a certain order, the fio configuration files let you do that. 

Also, in both cases the verify option has no effect, you can remove it. Lastly the options used in the first test are not the same as in the last test.

2020-05-21 12:57 UTC, gila commented on scale-test/fiopvctemplate.yaml
> +      storage: 10G
You allocate 10GB but you only create a file of 3GB why is that?

2020-05-21 12:57 UTC, gila commented on scale-test/fioload-template.yaml
> +---
This only ever does read. By default, cstor is configured with 4GB iirc, so let's say its 3GB of ARC. Most IO will be in memory once the file is laid out. 

Also, the iodepth of 2 is not a realistic value, it should match the value that the target supports.

2020-05-21 12:57 UTC, gila commented on scale-test/fiopvctemplate.yaml
> +  storageClassName: cstor2
where is the storage class defined?

2020-05-21 12:57 UTC, gila commented on scale-test/fiotemplate.yaml
> +    - 'fio --blocksize=@bs@ --verify=0 --randrepeat=0 --filename=/mnt/file1 --ioengine=libaio --readwrite=randread --runtime=15s --time_based --ramp_time=2s --size=3G --name=test --numjobs=8 --direct
For this, the same comments apply as to the other template file

2021-06-07 14:34 UTC, merged